name: CI

on:
  # allows us to run workflows manually
  workflow_dispatch:

  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ubuntu:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Prepare Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.2
      with:
        version: 1.4.309.0
        cache: true

    - name: Apt dependencies
      shell: bash
      run: |
        sudo apt -y update
        sudo apt-get update && sudo apt-get install -y libpthread-stubs0-dev
        sudo apt install -y libx11-xcb-dev \
                            xorg-dev \
                            libxinerama-dev \
                            libglu1-mesa-dev \
                            freeglut3-dev \
                            mesa-common-dev

    - name: Update CMake
      uses: ssrobins/install-cmake@v1
      with:
        version: 3.24.3
        cache: true

    - name: Build Shared
      shell: bash
      run: |
        export LD_LIBRARY_PATH=$VULKAN_SDK/lib:$LD_LIBRARY_PATH
        mkdir bld-shared
        cd bld-shared
        cmake --version
        cmake .. -DGPRT_BUILD_SHARED=ON
        make VERBOSE=1 -j4

    - name: Build Static
      shell: bash
      run: |
        export LD_LIBRARY_PATH=$VULKAN_SDK/lib:$LD_LIBRARY_PATH
        mkdir bld-static
        cd bld-static
        cmake --version
        cmake ..
        make VERBOSE=1 -j4

    # Useful for debugging
    # - name: Debug with tmate on failure
    #   if: ${{ failure() }}
    #   uses: mxschmitt/action-tmate@v3

  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Prepare Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.2
      with:
        version: 1.4.309.0
        cache: true

    - name: Update CMake
      uses: ssrobins/install-cmake@v1
      with:
        version: 3.24.3
        cache: true

    - name: Build
      shell: bash
      run: |
        mkdir bld
        cd bld
        cmake --version
        cmake .. -DVulkan_BIN_DIR=$HOME/bin
        cmake --build .
