name: Documentation

on:
  push:
    branches:
      - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Prepare Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r ./docs/requirements.txt

      - name: Prepare Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: 1.4.309.0
          cache: true

      - name: Apt dependencies
        shell: bash
        run: |
          sudo apt -y update
          sudo apt install -y xorg-dev \
                              libxinerama-dev \
                              libglu1-mesa-dev \
                              freeglut3-dev \
                              mesa-common-dev \
                              doxygen
      - name: Update CMake
        uses: ssrobins/install-cmake@v1
        with:
          version: 3.24.3
          cache: true

      - name: Build Documentation
        shell: bash
        run: |
          mkdir bld
          cd bld
          cmake --version
          cmake .. -DBUILD_DOC=ON
          cmake --build . --target sphinx --config Release
      - name: Setup Pages
        uses: actions/configure-pages@v2
  #     - name: Setup tmate session
  #       uses: mxschmitt/action-tmate@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './build/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
